# Generated by Django 4.2.3 on 2023-07-07 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_name_customuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('content', models.TextField(max_length=1000, verbose_name='content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='post-created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.customuser')),
            ],
        ),
    ]
