# Generated by Django 4.2.3 on 2023-07-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='user-created'),
        ),
    ]
