# Generated by Django 4.2.3 on 2023-07-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_customuser_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='founded',
            field=models.BooleanField(default=False, verbose_name='founded'),
        ),
    ]
