# Generated by Django 4.2.3 on 2023-07-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_post_founded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='null', max_length=100, unique=True, verbose_name='title'),
            preserve_default=False,
        ),
    ]
