# Generated by Django 4.2.3 on 2023-07-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_content_post_announcement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
