# Generated by Django 4.2.3 on 2023-07-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Image'),
        ),
    ]
