# Generated by Django 4.2.3 on 2023-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='announcement',
            field=models.TextField(default='Tidak ada konten', max_length=1000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='Tidak ada judul', max_length=100, verbose_name='title'),
        ),
    ]
